@startuml
package "Ui Layer" {
    left to right direction

    class AirplaneDataCreateNewUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + input_name()
        + input_manufacturer()
        + input_type()
        + input_seats()
        + new_created()
        + create_new_sequence()
        + input_prompt()
    }
    class AirplaneDataEditUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + airplane_data_edit_output()
        + edit_data()
        + input_prompt()
    }
    class AirplaneDataUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + airplane_data_output()
        + input_prompt()
    }

    class DestinationDataCreateNewUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + input_city()
        + input_airport()
        + input_country()
        + input_distance()
        + input_travel_time()
        + input_emerg_contact_name()
        + input_emerg_contact_phone_number()
        + new_created()
        + input_prompt()
    }
    class DestinationDataEditUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + destination_data_edit_output()
        + edit_data_emergency_name()
        + edit_data_emergency_phone()
        + input_prompt()

    }
    class DestinationDataUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + destination_data_output()
        + input_prompt()
    }
    class EmployeeDataCreateNewUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + input_employee_type()
        + input_employee_role()
        + input_airplane_type()
        + input_name()
        + input_ssn()
        + input_phone()
        + input_address()
        + input_email()
        + input_home_phone()
        + new_created()
        + create_new_sequence()
        + input_prompt() 
    }
    
    class EmployeeDataEditUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + employee_data_edit_output():
        + edit_data(changed_data)
        + input_prompt()


    }
    class EmployeeDataUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + all_employees_detailed()
        + pilots_detailed()
        + flight_attendants_detailed()
        + pilot_sorted_by_type()
        + pilot_specific_type()
        + input_airplane_type()
        + input_prompt()
    }
    class EmployeeSchedulesUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + employee_schedules_output()
        + input_prompt()
        + print_employees_all(print_format, line_num)
        + print_employees_working(print_format, line_num)
        + print_employees_not_working(print_format, line_num)
        + innitiate_and_switch_lists(date)
        + input_prompt()
    }

    class EmployeeScheduleSpecificUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + specific_employee_weekly_schedule(destination_list)
        + input_prompt()

    }


    class FlightSchedulesUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        - user : user
        + flight_schedules_output(printed_data, start_date, end_date)
        + innitiate_and_switch_lists(time, start_date)
        + input_prompt()
    }

    class FlightSchedulesCreateNewUI{
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        + input_departure_day()
        + input_departure_time()
        + input_return_time()
        + input_destination()
        + input_plane()
        + new_created()
        + create_new_sequence()
    }

    class FlightSchedulesStaffTripsUI {
        - PrintUi : PrintFunctions()
        - Logic : LogicLayerAPI()
        - trip_id : trip_id
        + show_staff_status()
        + assign_captain()
        + assign_copilot()
        + assign_sr_flight_attendant()
        + assign_flight_attendant()
        + innitiate_dict_lists()
        + innitiate_crew_dicts()
        + input_prompt()
    }

    class LoginUI{
        - PrintUi : PrintFunctions()
        + login_output()
        + input_prompt()
    }
    class MainMenuUI{
        - PrintUi : PrintFunctions()
        - user : user
        + main_menu_output()
        + input_prompt()
    }
    class PrintFunctions{
        + empty_line()
        + end_line()
        + allign_left()
        + allign_center()
        + print_header()
        + logo1()
        + logo2()
        + logo()
        + auto_shorten_name()
        + print_airplane_type_table()
        + print_destination_table()
        + print_airplane_table()
        + print_available_planes()
        + print_flight_schedule_table()
        + print_employee_schedule_table()
        + print_employee_table_detailed()
        + print_pilots_table_detailed()
        + print_flight_attendants_table_detailed()
    }

    LoginUI --> MainMenuUI
    MainMenuUI --> AirplaneDataUI
    MainMenuUI --> DestinationDataUI
    MainMenuUI --> EmployeeDataUI
    MainMenuUI --> EmployeeSchedulesUI
    MainMenuUI --> FlightSchedulesUI
    AirplaneDataUI --> AirplaneDataCreateNewUI
    AirplaneDataUI --> AirplaneDataEditUI
    DestinationDataUI --> DestinationDataCreateNewUI
    DestinationDataUI --> DestinationDataEditUI
    EmployeeDataUI --> EmployeeDataCreateNewUI
    EmployeeDataUI --> EmployeeDataEditUI
    EmployeeSchedulesUI --> EmployeeScheduleSpecificUI
    FlightSchedulesUI --> FlightSchedulesCreateNewUI
    FlightSchedulesUI --> FlightSchedulesStaffTripsUI


    note "The UI layer depends on the LogicLayerAPI" as NoteUILayer


}
@enduml

